[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vf_solana_vault = "2oQy57MWn8xmFBP1g4xi7cXdzTtut7UbdqNmVEzubUfH"

[programs.testnet]
vf_solana_vault = "2oQy57MWn8xmFBP1g4xi7cXdzTtut7UbdqNmVEzubUfH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 5000
shutdown_wait = 2000

[test.validator]
url = "https://api.mainnet-beta.solana.com"